'use client';

import { useMemo, useState } from 'react';

type Incident = { id:string; name:string; severity:string; service:string; logs:string; cause:string; confidence:number; evidence:string[]; alternatives:string[]; steps:string[]; fix:string; };

const incidents: Incident[] = [
 {id:'auth-401',name:'Expired authentication token',severity:'Critical',service:'Identity Gateway',logs:'2026-08-16T10:42:11Z ERROR auth.middleware\nGET /api/settlements/overview 401\nAuthorization token validation failed: exp claim is in the past\nrequest_id=req_7f91',cause:'The access token is expired. The gateway rejects the request before it reaches the settlements service.',confidence:96,evidence:['401 response from auth middleware','"exp claim is in the past"','Failure occurs before downstream service invocation'],alternatives:['Incorrect Authorization header — 3%','Missing permission scope — 1%'],steps:['Decode the token and verify exp against current UTC time','Refresh the access token','Retry the request and confirm a 2xx response','If repeated, inspect clock skew between gateway and issuer'],fix:'Refresh the access token and ensure the client sends Authorization: Bearer <token>. Add a proactive refresh window before expiry.'},
 {id:'db-timeout',name:'Database connection timeout',severity:'High',service:'Orders API',logs:'2026-08-16T11:07:44Z ERROR orders.repository\nPOST /api/orders 500\npsycopg2.OperationalError: connection pool exhausted\nactive=50 idle=0 waiters=37',cause:'The database connection pool is exhausted. Requests queue until the timeout and surface as 500s.',confidence:91,evidence:['pool exhausted','50 active connections with 37 waiters','500 occurs in repository layer'],alternatives:['Database is slow — 6%','Network packet loss — 3%'],steps:['Check DB CPU/connections and long-running queries','Inspect pool size versus application concurrency','Identify leaked/unclosed connections','Reduce query latency and retest under load'],fix:'Close connections reliably, tune pool size, and add pool saturation metrics/alerts. Do not blindly increase the pool without checking the database connection limit.'},
 {id:'kafka-lag',name:'Kafka consumer lag spike',severity:'High',service:'Notifications Worker',logs:'2026-08-16T12:18:02Z WARN consumer\npartition=notifications-7 lag=182441\ncommit latency=4.8s\nrebalance in progress',cause:'Repeated consumer rebalances are preventing stable partition ownership, causing backlog growth.',confidence:88,evidence:['rebalance in progress','high commit latency','single partition has rapidly growing lag'],alternatives:['Producer traffic spike — 8%','Downstream email provider slow — 4%'],steps:['Inspect consumer group rebalance events','Check max.poll.interval.ms and processing time','Inspect consumer errors and GC pauses','Stabilize the group, then drain backlog'],fix:'Keep message processing within poll interval, reduce per-message work, and tune consumer concurrency carefully. Add lag and rebalance alerts.'},
 {id:'endpoint',name:'Incorrect API endpoint',severity:'Medium',service:'Payments Client',logs:'2026-08-16T13:02:31Z WARN http.client\nPOST /v1/payment 404\nserver route: POST /v1/payments\nrequest_id=req_88ad',cause:'The client calls /v1/payment while the server exposes /v1/payments.',confidence:99,evidence:['client requested /v1/payment','server route is /v1/payments','404 is returned by routing layer'],alternatives:['API version mismatch — 1%'],steps:['Update client route to /v1/payments','Add contract tests against the OpenAPI spec','Deploy and verify the request reaches the handler'],fix:'Change the client endpoint from /v1/payment to /v1/payments and add an API contract test to prevent route drift.'},
 {id:'config',name:'Missing production configuration',severity:'Medium',service:'Checkout API',logs:'2026-08-16T13:26:18Z ERROR checkout\nPOST /api/checkout 500\nError: PAYMENT_WEBHOOK_SECRET is undefined\nstack: checkout/webhook.ts:42',cause:'A required environment variable is absent in the production deployment.',confidence:98,evidence:['explicit undefined configuration error','failure originates in webhook initialization','variable name identifies the missing secret'],alternatives:['Secret value is invalid — 2%'],steps:['Check deployment environment variables','Add PAYMENT_WEBHOOK_SECRET to production scope','Redeploy and verify secret injection','Rotate the secret if it may have been exposed'],fix:'Configure PAYMENT_WEBHOOK_SECRET in the production environment and redeploy. Add startup validation for required configuration.'}
];

function score(logs:string, i:Incident){
 const terms = i.name.toLowerCase().split(/[^a-z0-9]+/).filter(Boolean);
 const low=logs.toLowerCase(); const hits=terms.filter(t=>t.length>3 && low.includes(t)).length;
 return Math.min(99, Math.max(55, i.confidence - 18 + hits*7));
}

export default function Home(){
 const [text,setText]=useState(incidents[0].logs); const [selected,setSelected]=useState(incidents[0]); const [tab,setTab]=useState('investigate'); const [busy,setBusy]=useState(false);
 const ranked=useMemo(()=>incidents.map(i=>({...i,match:score(text,i)})).sort((a,b)=>b.match-a.match),[text]);
 const investigate=()=>{setBusy(true);setTimeout(()=>{setSelected(ranked[0]);setTab('investigate');setBusy(false)},550)};
 return <main className="shell">
   <header className="topbar"><div className="brand"><div className="logo">B</div><div><b>BugLens</b><span>AI Root-Cause Investigator</span></div></div><div className="status"><i/> Demo environment <strong>● Live</strong></div></header>
   <section className="hero"><div><p className="eyebrow">PRODUCTION INCIDENT INTELLIGENCE</p><h1>Turn noisy logs into<br/><em>actionable diagnoses.</em></h1><p className="sub">A grounded AI investigation workflow that extracts signals, retrieves similar incidents, ranks root causes and produces a safe remediation path.</p></div><div className="metrics"><div><b>5</b><span>Failure scenarios</span></div><div><b>93%</b><span>Avg. confidence</span></div><div><b>4</b><span>Evidence signals</span></div></div></section>
   <section className="workspace">
    <aside className="sidebar"><div className="side-title">Demo scenarios</div>{incidents.map(i=><button key={i.id} className={'scenario '+(selected.id===i.id?'active':'')} onClick={()=>{setText(i.logs);setSelected(i)}}><span className={'dot '+i.severity.toLowerCase()}/><span><b>{i.name}</b><small>{i.service}</small></span><span className="chev">›</span></button>)}<div className="architecture"><span>PIPELINE</span><div>Logs <b>→</b> Signals</div><div>Signals <b>→</b> Retrieval</div><div>Retrieval <b>→</b> Diagnosis</div></div></aside>
    <div className="mainpanel"><div className="inputcard"><div className="cardhead"><div><span className="label">INCIDENT INPUT</span><h2>Paste application logs</h2></div><button className="ghost" onClick={()=>setText('')}>Clear</button></div><textarea value={text} onChange={e=>setText(e.target.value)} placeholder="Paste stack traces, logs, API responses or alerts..."/><div className="inputfoot"><span>Local-first demo · No logs leave your browser</span><button className="primary" onClick={investigate}>{busy?'Analyzing…':'✦ Investigate incident'}</button></div></div>
      <div className="tabs">{['investigate','evidence','evaluation'].map(t=><button className={tab===t?'on':''} onClick={()=>setTab(t)} key={t}>{t==='investigate'?'Diagnosis':t==='evidence'?'Evidence':'Evaluation'}</button>)}</div>
      {tab==='investigate'&&<div className="results"><div className="diagnosis card"><div className="resulttop"><span className={'pill '+selected.severity.toLowerCase()}>{selected.severity} severity</span><span className="confidence">Confidence <b>{selected.confidence}%</b></span></div><h2>{selected.cause}</h2><p className="explain">BugLens ranked this cause highest from the log signals and matching incident patterns. The recommendation is deliberately evidence-backed rather than a free-form guess.</p><div className="causegrid"><div><span className="label">PROBABLE ROOT CAUSE</span><strong>{selected.name}</strong></div><div><span className="label">AFFECTED SERVICE</span><strong>{selected.service}</strong></div></div></div>
       <div className="twocol"><div className="card"><span className="label">ALTERNATIVE CAUSES</span>{selected.alternatives.map((a,n)=><div className="alt" key={a}><span>{n+2}</span><b>{a.split(' — ')[0]}</b><small>{a.split(' — ')[1]}</small></div>)}</div><div className="card"><span className="label">INVESTIGATION PATH</span>{selected.steps.map((s,n)=><div className="step" key={s}><i>{n+1}</i><span>{s}</span></div>)}</div></div>
       <div className="fix card"><div><span className="label">RECOMMENDED FIX</span><p>{selected.fix}</p></div><button className="copy" onClick={()=>navigator.clipboard?.writeText(selected.fix)}>Copy fix</button></div></div>}
      {tab==='evidence'&&<div className="card evidence"><span className="label">WHY BUGLENS BELIEVES THIS</span>{selected.evidence.map((e,n)=><div className="evidenceRow" key={e}><span>{String(n+1).padStart(2,'0')}</span><code>{e}</code><b>matched</b></div>)}<div className="logpreview"><span className="label">RAW INPUT</span><pre>{text || 'No log input.'}</pre></div></div>}
      {tab==='evaluation'&&<div className="card evaluation"><span className="label">OFFLINE BENCHMARK</span><h2>Known failure scenarios</h2><p>Each demo scenario has a ground-truth root cause. The matcher ranks the correct incident from the input signals.</p>{ranked.map(i=><div className="evalrow" key={i.id}><span className="evaldot"/><b>{i.name}</b><span>{i.match}% match</span><strong>{i.id===selected.id?'Selected':'Candidate'}</strong></div>)}<div className="benchmark"><b>5/5</b><span>scenarios covered in demo dataset</span></div></div>}
    </div>
   </section>
   <footer><span>BugLens v1.0</span><span>Structured diagnosis · Evidence grounded · Interview demo ready</span></footer>
 </main>
}
