'use client';

import { useMemo, useState } from 'react';

type Analysis = {
  id: string; title: string; summary: string; risk: number; confidence: number;
  impact: { name: string; level: 'high'|'medium'|'low'; why: string }[];
  assumptions: string[]; tests: string[]; rollout: string[]; rollback: string; evidence: string[];
};

const scenarios: Analysis[] = [
  {id:'fee',title:'Add a 10% convenience fee to checkout for international cards',summary:'This change crosses pricing, checkout, payment authorization and reporting boundaries. The highest risk is inconsistent totals between the client, order service and payment provider.',risk:78,confidence:94,impact:[{name:'Checkout UI',level:'high',why:'Must display fee, total and disclosure consistently.'},{name:'Checkout API',level:'high',why:'Server must calculate the authoritative amount.'},{name:'Pricing logic',level:'high',why:'Fee eligibility and rounding become new business rules.'},{name:'Database',level:'medium',why:'Order and invoice records need auditable fee fields.'},{name:'Payment gateway',level:'high',why:'Authorized amount must include the fee.'},{name:'Analytics',level:'medium',why:'Revenue and conversion metrics can shift.'}],assumptions:['The fee applies only to international card payments.','The fee is calculated before authorization and is non-taxable.','Existing orders must keep their original totals.'],tests:['Domestic card → no fee','International card → exactly 10% fee','Rounding at ₹0.01 boundaries','Retry/payment webhook preserves the same total','Refund reverses the fee correctly'],rollout:['Add server-side calculation behind a feature flag','Enable for internal/test cards','Release to 5% of eligible traffic','Compare payment totals and conversion metrics','Gradually move to 100%'],rollback:'Disable the feature flag. Keep stored fee fields for auditability; do not rewrite historical orders.',evidence:['“international cards” → payment + eligibility path','“10%” → pricing/rounding rules','“checkout” → UI + API + order persistence']},
  {id:'auth',title:'Replace the current authentication provider with Auth0',summary:'The change affects identity, sessions, authorization claims and every service that trusts the current token issuer. The biggest risk is an inconsistent identity model during migration.',risk:86,confidence:92,impact:[{name:'Login UI',level:'high',why:'Redirects, callbacks and error states change.'},{name:'API Gateway',level:'high',why:'Token issuer and JWKS validation change.'},{name:'Authorization',level:'high',why:'Claims/roles must map exactly.'},{name:'Database',level:'medium',why:'User identity IDs may need a migration map.'},{name:'Background jobs',level:'medium',why:'Service-to-service credentials may differ.'},{name:'Observability',level:'low',why:'Auth failure dashboards need new dimensions.'}],assumptions:['Existing users must keep access without re-registration.','Roles/scopes have an equivalent representation.','A dual-validation period is possible.'],tests:['Existing user logs in and retains account','Role/permission matrix remains identical','Expired token is rejected','Old and new issuer tokens behave correctly during migration','Logout invalidates the new session'],rollout:['Introduce provider adapter','Dual-validate old and new tokens','Migrate a small internal cohort','Monitor 401/403 rates','Migrate users gradually and retire old issuer'],rollback:'Route authentication back to the old provider while preserving the identity mapping. Keep the adapter until migration is complete.',evidence:['“replace authentication provider” → identity + token trust boundary','“current” → migration/compatibility requirement','Provider change → issuer, claims and session lifecycle']},
  {id:'kafka',title:'Publish an OrderCreated event to Kafka after checkout',summary:'The visible feature is small, but it introduces an asynchronous reliability boundary. The critical design question is preventing an order from being committed without its event.',risk:72,confidence:90,impact:[{name:'Checkout API',level:'high',why:'Must publish after a successful order commit.'},{name:'Order DB',level:'high',why:'Transaction/event consistency is required.'},{name:'Kafka',level:'high',why:'New topic, partitioning and delivery semantics.'},{name:'Consumers',level:'medium',why:'Downstream services must handle duplicates.'},{name:'Observability',level:'medium',why:'Lag, failures and publish latency need alerts.'},{name:'Retry/DLQ',level:'medium',why:'Failed consumers need recovery semantics.'}],assumptions:['Consumers can be idempotent.','Ordering is required per order, not globally.','At-least-once delivery is acceptable.'],tests:['Order commit + event publish success','DB commit succeeds but Kafka publish fails','Duplicate event is consumed twice','Kafka unavailable during checkout','Consumer replays an old event'],rollout:['Create topic and schema','Implement transactional outbox','Shadow-publish events','Enable one consumer','Monitor lag and duplicate rate','Expand consumers'],rollback:'Stop consumers and publishing while leaving the outbox intact. Drain or replay events after the issue is resolved.',evidence:['“after checkout” → ordering/transaction boundary','“Kafka” → async delivery + consumer failure modes','“OrderCreated” → event schema and idempotency']},
  {id:'db',title:'Migrate the orders table from PostgreSQL to a partitioned design',summary:'Partitioning can improve scale, but it changes indexes, query plans, maintenance and migration strategy. The main risk is queries that silently stop using the intended partition key.',risk:64,confidence:89,impact:[{name:'Order repository',level:'high',why:'Queries and indexes need partition-aware validation.'},{name:'PostgreSQL',level:'high',why:'DDL, partitions and maintenance behavior change.'},{name:'Reporting',level:'medium',why:'Large scans may behave differently.'},{name:'Migration jobs',level:'high',why:'Backfill must be resumable and verifiable.'},{name:'API',level:'low',why:'Contract should remain stable.'},{name:'Monitoring',level:'medium',why:'Query latency and partition skew need visibility.'}],assumptions:['Application APIs remain unchanged.','A partition key with stable distribution exists.','Backfill can run without blocking writes.'],tests:['Reads across old/new partitions','Insert at partition boundary','Index-backed lookup latency','Backfill restart after failure','Partition skew under realistic data'],rollout:['Create partitioned shadow table','Backfill in batches','Dual-write and compare counts','Validate query plans','Switch reads','Retire legacy table after verification'],rollback:'Switch reads back to the legacy table and stop dual-writes only after confirming data consistency.',evidence:['“partitioned design” → query plan/index impact','“orders table” → persistence + migration scope','Migration wording → dual-write/backfill requirement']}
];

function analyzeCustom(input:string): Analysis {
  const s=input.toLowerCase();
  const auth=s.includes('auth')||s.includes('login')||s.includes('identity');
  const data=s.includes('database')||s.includes('postgres')||s.includes('migrat');
  const event=s.includes('kafka')||s.includes('event')||s.includes('queue');
  const payment=s.includes('payment')||s.includes('checkout')||s.includes('fee');
  const base=payment?scenarios[0]:auth?scenarios[1]:event?scenarios[2]:data?scenarios[3]:scenarios[0];
  return {...base,id:'custom',title:input,summary:`AI-assisted analysis detected signals associated with ${payment?'payments and pricing':auth?'identity and access control':event?'asynchronous event delivery':data?'data persistence and migration':'cross-service change management'}. The result is a starting hypothesis that should be validated against the real architecture.`,risk:Math.min(95,base.risk+(input.length>90?5:0)),confidence:82, evidence:[`Detected change signal: ${payment?'payment/checkout':auth?'authentication':event?'event/async':data?'database/migration':'general feature change'}`, 'Scope crosses at least two engineering boundaries','Change requires explicit rollout and rollback controls']};
}

export default function Home(){
  const [id,setId]=useState('fee');
  const [input,setInput]=useState(scenarios[0].title);
  const [tab,setTab]=useState<'impact'|'risk'|'tests'|'rollout'|'evidence'>('impact');
  const [analyzing,setAnalyzing]=useState(false);
  const selected=useMemo(()=>id==='custom'?analyzeCustom(input):scenarios.find(x=>x.id===id)!,[id,input]);
  const choose=(s:Analysis)=>{setId(s.id);setInput(s.title);setTab('impact');};
  const run=()=>{setAnalyzing(true);setTimeout(()=>{setId('custom');setTab('impact');setAnalyzing(false)},650)};
  const nodes=['Checkout UI','API','Business Logic','Database','External Service'];
  return <main className="app">
    <header className="nav"><div className="brand"><div className="mark">⌁</div><div><b>ChangeRadar</b><span>AI Change Impact Copilot</span></div></div><div className="navright"><span className="live"><i/> Local inference</span><button className="help" onClick={()=>alert('ChangeRadar extracts signals from a proposed change, maps likely system boundaries, synthesizes risk and produces an action plan. The demo uses a deterministic local reasoning engine; an LLM provider can replace the reasoning layer without changing the UI contract.')}>How it works</button></div></header>
    <section className="hero"><div><div className="eyebrow">ENGINEERING IMPACT INTELLIGENCE</div><h1>Before you ship a change,<br/><em>see what it might break.</em></h1><p>Paste a requirement, architecture change or migration idea. ChangeRadar turns it into an impact map, risk model, edge-case checklist and rollout plan.</p></div><div className="heroBadge"><strong>5</strong><span>system boundaries<br/>mapped instantly</span></div></section>
    <div className="layout">
      <aside className="presets"><div className="sectionTitle">DEMO SCENARIOS</div>{scenarios.map(s=><button key={s.id} className={id===s.id?'preset active':'preset'} onClick={()=>choose(s)}><span className="pulse"/><span><b>{s.title}</b><small>Risk {s.risk}/100</small></span><span>›</span></button>)}<div className="miniFlow"><div className="sectionTitle">REASONING PIPELINE</div><p>Change <b>→</b> Signals</p><p>Signals <b>→</b> Impact Map</p><p>Impact <b>→</b> Risk</p><p>Risk <b>→</b> Action Plan</p></div></aside>
      <section className="workspace"><div className="inputBox"><div><span className="label">PROPOSED CHANGE</span><h2>What are you planning to change?</h2></div><textarea value={input} onChange={e=>{setInput(e.target.value);setId('custom')}}/><div className="inputBottom"><span>Private by design · nothing leaves your browser</span><button onClick={run} disabled={analyzing}>{analyzing?'Analyzing signals…':'✦ Analyze change'}</button></div></div>
        <div className="summary"><div><span className="label">RISK SCORE</span><strong className={selected.risk>=80?'danger':selected.risk>=65?'warn':'safe'}>{selected.risk}<small>/100</small></strong></div><div><span className="label">MODEL CONFIDENCE</span><strong>{selected.confidence}<small>%</small></strong></div><div><span className="label">IMPACTED AREAS</span><strong>{selected.impact.length}<small> boundaries</small></strong></div><div className="riskBar"><span style={{width:`${selected.risk}%`}}/></div></div>
        <div className="tabs">{[['impact','Impact Map'],['risk','Risks & Assumptions'],['tests','Tests'],['rollout','Rollout'],['evidence','Evidence']] .map(([key,label])=><button key={key} className={tab===key?'on':''} onClick={()=>setTab(key as typeof tab)}>{label}</button>)}</div>
        {tab==='impact'&&<div className="content"><div className="card"><div className="cardTitle"><span className="label">SYSTEM IMPACT MAP</span><span className="legend"><i/>high <i/>medium <i/>low</span></div><div className="map">{nodes.map((n,i)=>{const hit=selected.impact.find(x=>x.name.includes(n.split(' ')[0])||x.name.includes(n));return <div className="mapItem" key={n}><div className={'node '+(hit?.level||'low')}><span>{['▣','↗','◈','▤','◎'][i]}</span><b>{n}</b><small>{hit?.level||'low'} impact</small></div>{i<nodes.length-1&&<div className="connector">→</div>}</div>})}</div></div><div className="grid2"><div className="card"><span className="label">LIKELY IMPACT</span>{selected.impact.map(x=><div className="impactRow" key={x.name}><span className={'tiny '+x.level}/><div><b>{x.name}</b><small>{x.why}</small></div></div>)}</div><div className="card"><span className="label">WHAT COULD GO WRONG?</span>{selected.tests.slice(0,4).map((x,i)=><div className="bullet" key={x}><span>{i+1}</span>{x}</div>)}</div></div></div>}
        {tab==='risk'&&<div className="grid2 content"><div className="card"><span className="label">HIDDEN ASSUMPTIONS</span>{selected.assumptions.map(x=><div className="bullet" key={x}><span>!</span>{x}</div>)}</div><div className="card"><span className="label">RISK SYNTHESIS</span><div className="riskExplain"><strong>{selected.risk>=80?'HIGH':'MODERATE'} RISK</strong><p>{selected.summary}</p><div className="meter"><span style={{width:`${selected.risk}%`}}/></div></div></div></div>}
        {tab==='tests'&&<div className="card content"><div className="cardTitle"><span className="label">RECOMMENDED TEST MATRIX</span><button className="smallBtn" onClick={()=>navigator.clipboard?.writeText(selected.tests.join('\n'))}>Copy tests</button></div>{selected.tests.map((x,i)=><div className="test" key={x}><span>{String(i+1).padStart(2,'0')}</span><div><b>{x}</b><small>{i<2?'Critical path':'Edge / failure path'}</small></div><em>Suggested</em></div>)}</div>}
        {tab==='rollout'&&<div className="grid2 content"><div className="card"><span className="label">SAFE ROLLOUT</span>{selected.rollout.map((x,i)=><div className="step" key={x}><span>{i+1}</span>{x}</div>)}</div><div className="card rollback"><span className="label">ROLLBACK PLAN</span><p>{selected.rollback}</p><button className="smallBtn" onClick={()=>navigator.clipboard?.writeText(selected.rollback)}>Copy rollback</button></div></div>}
        {tab==='evidence'&&<div className="grid2 content"><div className="card"><span className="label">SIGNALS DETECTED</span>{selected.evidence.map((x,i)=><div className="evidence" key={x}><span>0{i+1}</span><b>{x}</b><em>matched</em></div>)}</div><div className="card"><span className="label">WHAT WOULD CHANGE MY MIND?</span><p className="changeMind">Ask the architecture owner to verify the boundaries above. If any detected assumption is false, re-run the analysis with the missing constraint. This keeps the tool hypothesis-driven instead of pretending the first answer is certain.</p></div></div>}
      </section>
    </div>
    <footer><b>ChangeRadar v1.0</b><span>AI-assisted engineering impact analysis · LLM-ready architecture · Interview demo</span></footer>
  </main>
}
